#!/bin/sh

xrdb -merge .Xresources &

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi




# dispaly res
# xrandr --output Virtual-1 --mode 1920x1080 & 

# compositor
picom &
hsetroot -fill Pictures/Wall3.jpg &
copyq &
xautolock -time 5 -locker "systemctl suspend" -detectsleep &
xrandr --output eDP-1 --gamma 1.0:0.88:0.76 &
dunst &
/home/kunal/.local/bin/lb &
# status bar

while true; do
	xsetroot -name "|| Bat: $(acpi | awk '{print $4}i') $(acpi | awk '{print $5}') || $(date '+%a %H:%M %Y-%m-%d') ||"
	sleep 5s
done &

# execute dwm
exec /home/kunal/.local/bin/dwm

